namespace Documentation
{
    partial class CIVIL
    {
        /// <summary>
        /// المتغيرات اللازمة للنموذج.
        /// </summary>
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button6;

        /// <summary>
        /// تنظيف الموارد التي تستخدمها.
        /// </summary>
        /// <param name="disposing">إذا كان يجب التخلص من الموارد المخصصة.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region "Code Generated by Windows Forms Designer"
        private void InitializeComponent()
        {
            button1 = new Button();
            button6 = new Button();
            label1 = new Label();
            comboBox1 = new ComboBox();
            SuspendLayout();
            // 
            // button1
            // 
            button1.BackColor = SystemColors.ControlDark;
            button1.FlatStyle = FlatStyle.Flat;
            button1.Font = new Font("Segoe UI", 13F);
            button1.Location = new Point(700, 534);
            button1.Name = "button1";
            button1.Size = new Size(311, 65);
            button1.TabIndex = 1;
            button1.Text = "B A C k";
            button1.UseVisualStyleBackColor = false;
            button1.Click += Button1_Click;
            // 
            // button6
            // 
            button6.BackColor = Color.Teal;
            button6.FlatStyle = FlatStyle.Flat;
            button6.Font = new Font("Segoe UI", 13F);
            button6.Location = new Point(1185, 281);
            button6.Name = "button6";
            button6.Size = new Size(375, 90);
            button6.TabIndex = 2;
            button6.Text = "New";
            button6.UseVisualStyleBackColor = false;
            button6.Click += Button6_Click;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.BackColor = Color.Transparent;
            label1.Font = new Font("Segoe UI", 25F);
            label1.Location = new Point(665, 59);
            label1.Name = "label1";
            label1.Size = new Size(211, 67);
            label1.TabIndex = 3;
            label1.Text = "C  I V I L";
            // 
            // comboBox1
            // 
            comboBox1.FormattingEnabled = true;
            comboBox1.Location = new Point(126, 281);
            comboBox1.Name = "comboBox1";
            comboBox1.Size = new Size(455, 33);
            comboBox1.TabIndex = 4;
            comboBox1.SelectedIndexChanged += comboBox1_SelectedIndexChanged;
            // 
            // CIVIL
            // 
            BackgroundImage = Properties.Resources.WhatsApp_Image_2024_12_03_at_3_23_56_AM;
            ClientSize = new Size(1633, 759);
            Controls.Add(comboBox1);
            Controls.Add(label1);
            Controls.Add(button6);
            Controls.Add(button1);
            MaximizeBox = false;
            MdiChildrenMinimizedAnchorBottom = false;
            Name = "CIVIL";
            ShowIcon = false;
            ShowInTaskbar = false;
            Text = "CIVIL Form";
            Load += CIVIL_Load;
            ResumeLayout(false);
            PerformLayout();
        }
        #endregion

        private Label label1;
        private ComboBox comboBox1;
    }
}
